### PR TITLE
Adding overwrite functionality

### PR DESCRIPTION
**Pull request by cccs-mdr**

### CODE REVIEW

**Comment by cccs-mdr** [comment]
For some reason I'm getting a test error on my local machine, I committed a log file if reviewers can take a look?

**Comment by cccs-mdr** [comment]
Also, this doesn't seem to run well on the test server, getting a syntax error? Ubuntu 20.04, Python 3.9

**Comment by sa-spellbook** [comment]
Static Badge

<details>
    <summary>Command Output</summary>

    howler/api/v1/hit.py:286:26: F541 [*] f-string without any placeholders
    howler/api/v1/hit.py:289:19: F821 Undefined name `merge`
    howler/api/v1/hit.py:292:22: F821 Undefined name `Strategy`
    howler/api/v1/hit.py:294:18: F821 Undefined name `Strategy`
    howler/api/v1/hit.py:300:12: F821 Undefined name `HowlerValueError`
    howler/api/v1/hit.py:334:26: F821 Undefined name `OdmUpdateOperation`
    howler/api/v1/hit.py:339:31: F821 Undefined name `OdmUpdateOperation`
    howler/api/v1/hit.py:340:64: F821 Undefined name `json`
    howler/api/v1/hit.py:343:13: F821 Undefined name `OdmUpdateOperation`
    howler/api/v1/hit.py:344:17: F821 Undefined name `ESCollection`
    howler/api/v1/hit.py:353:29: F821 Undefined name `HitOperationType`
    howler/api/v1/hit.py:365:12: F821 Undefined name `HowlerValueError`
    howler/api/v1/hit.py:404:13: F821 Undefined name `OdmUpdateOperation`
    howler/api/v1/hit.py:405:64: F821 Undefined name `json`
    howler/api/v1/hit.py:409:17: F821 Undefined name `ESCollection`
    howler/api/v1/hit.py:422:13: F821 Undefined name `HowlerValueError`
    howler/api/v1/hit.py:422:41: F821 Undefined name `DataStoreException`
    howler/api/v1/hit.py:425:16: F821 Undefined name `internal_error`
    howler/api/v1/hit.py:458:36: F821 Undefined name `sanitize_lucene_query`
    howler/api/v1/hit.py:632:30: F821 Undefined name `HitStatusTransition`
    howler/api/v1/hit.py:636:24: F821 Undefined name `HitStatusTransition`
    howler/api/v1/hit.py:641:13: F821 Undefined name `WorkflowException`
    howler/api/v1/hit.py:641:32: F821 Undefined name `DataStoreException`
    howler/api/v1/hit.py:641:52: F821 Undefined name `InvalidDataException`
    howler/api/v1/hit.py:643:12: F821 Undefined name `VersionConflictException`
    howler/api/v1/hit.py:644:16: F821 Undefined name `conflict`
    howler/api/v1/hit.py:646:16: F821 Undefined name `internal_error`
    howler/api/v1/hit.py:673:23: F821 Undefined name `Comment`
    howler/api/v1/hit.py:725:21: F821 Undefined name `Comment`
    howler/api/v1/hit.py:732:12: F821 Undefined name `DataStoreException`
    howler/api/v1/hit.py:781:23: F821 Undefined name `Comment`
    howler/api/v1/hit.py:794:17: F821 Undefined name `difflib`
    howler/api/v1/hit.py:868:12: F821 Undefined name `DataStoreException`
    howler/api/v1/hit.py:1062:24: F821 Undefined name `conflict`
    Found 34 errors.
    [*] 1 fixable with the `--fix` option.
</details>

**Comment by sa-spellbook** [comment]
Static Badge

<details>
    <summary>Command Output</summary>

    howler/api/v1/hit.py:304:26: F541 [*] f-string without any placeholders
    Found 1 error.
    [*] 1 fixable with the `--fix` option.
</details>

**Pull request closed without merging**
